Repository jinsung99123/travel_muse_app, pull requests merged in 2025-06, with the labels that each got.

#18 [home] 홈화면 ui, 컴포넌트화
  lib/core/widgets/bottom_bar.dart
  lib/views/home/home_page.dart
  lib/views/home/widgets/info_banner.dart
  lib/views/home/widgets/popular_trips_list.dart
  lib/views/home/widgets/recommended_places_list.dart
  lib/views/home/widgets/recommended_restaurants_list.dart
  lib/views/home/widgets/section_title.dart
  lib/views/home/widgets/travel_register_button.dart
Labels: feat

#21 [Home] 스플레시 페이지 UI 구현
  lib/views/home/home_page.dart
  lib/views/splash/splash_page.dart
Labels: feat

#23 [Onboarding] 온보딩 ui 구현
  lib/main.dart
  lib/viewmodels/onboarding_view_model.dart
  lib/views/onboarding/onboarding_page.dart
  lib/views/onboarding/tabs/onboarding_tab_image.dart
  lib/views/onboarding/tabs/onboarding_tab_nickname.dart
  lib/views/onboarding/tabs/onboarding_tab_start_test.dart
  lib/views/onboarding/widgets/next_button.dart
  lib/views/onboarding/widgets/onboarding_tab_section.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#24 [plan] 장소 검색 및 리스트 페이지 ui
  lib/views/plan/place_search_page.dart
  lib/views/plan/widgets/plan_place_card.dart
  lib/views/plan/widgets/search_bar.dart
  lib/views/plan/widgets/search_result_list.dart
Labels: feat

#29 [plan]일정관리ui
  lib/views/plan/place_search/place_search_page.dart
  lib/views/plan/place_search/widgets/plan_place_card.dart
  lib/views/plan/place_search/widgets/search_bar.dart
  lib/views/plan/place_search/widgets/search_result_list.dart
  lib/views/plan/schedule/schedule_page.dart
  lib/views/plan/schedule/widgets/day_schedule_section.dart
  lib/views/plan/schedule/widgets/schedule_app_bar.dart
  lib/views/plan/schedule/widgets/schedule_place_card.dart
Labels: feat

#25 [preference]Ghghtls/issue20 성향테스트 질문 2가지 추가
  lib/core/widgets/bottom_bar.dart
  lib/views/home/widgets/info_banner.dart
  lib/views/home/widgets/popular_trips_list.dart
  lib/views/home/widgets/recommended_places_list.dart
  lib/views/home/widgets/recommended_restaurants_list.dart
  lib/views/home/widgets/section_title.dart
  lib/views/home/widgets/travel_register_button.dart
  lib/views/preference/preference_test_page.dart
  lib/views/preference/widgets/next_button.dart
  lib/views/preference/widgets/option_button.dart
  lib/views/preference/widgets/preference_questions.dart
  lib/views/preference/widgets/previousButton.dart
  lib/views/preference/widgets/question_card.dart
  lib/views/preference/widgets/question_list_view.dart
  lib/views/preference/widgets/result_view.dart
  lib/views/splash/splash_page.dart
Labels: feat

#39 [Plan] 달력 선택 페이지 ui구현
  lib/models/calendar_model.dart
  lib/providers/calendar_provider.dart
  lib/viewmodels/calendar_view_model.dart
  lib/views/calendar/calendar_page.dart
  lib/views/calendar/widgets/calendar_day_builder.dart
  lib/views/calendar/widgets/calendar_header.dart
  lib/views/calendar/widgets/calendar_widget.dart
  pubspec.lock
  pubspec.yaml
  vscode/launch.json
Labels: feat

#40 [Location] Google Map API 연동
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Runner/Info.plist
  lib/views/location/map_page.dart
  pubspec.yaml
Labels: feat

#46 [preference] 성향테스트 파이어스토어 연동
  lib/models/preference_test_model.dart
  lib/providers/preference_test_provider.dart
  lib/repositories/preference_test_repository.dart
  lib/services/preference_test_service.dart
  lib/viewmodels/preference_test_view_model.dart
  lib/views/plan/location_setting/province_setting_page.dart
  lib/views/preference/widgets/result_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#48 fix: firebase 버전 충돌 해결
  pubspec.lock
  pubspec.yaml
Labels: fix

#57 [MyPage] 여행 일정/성향 목록 페이지 ui 구현
  lib/views/my_page/plan_list_page.dart
  lib/views/my_page/preference_list_page.dart
  lib/views/my_page/widgets/preference_card.dart
  lib/views/my_page/widgets/schedule_card.dart
Labels: feat

#60 [Plan]장소 선택 후 일정에 추가 및 Firebase 저장 기능 구현
  lib/models/plans.dart
  lib/providers/schedule_provider.dart
  lib/repositories/schedule_repository.dart
  lib/viewmodels/schedule_view_model.dart
  lib/viewmodels/search_view_model.dart
  lib/views/my_page/plan_list_page.dart
  lib/views/plan/location_setting/district_setting_page.dart
  lib/views/plan/place_search/place_search_page.dart
  lib/views/plan/place_search/widgets/plan_place_card.dart
  lib/views/plan/place_search/widgets/search_result_list.dart
  lib/views/plan/schedule/schedule_page.dart
  lib/views/plan/schedule/widgets/day_schedule_section.dart
  lib/views/plan/schedule/widgets/schedule_app_bar.dart
Labels: feat

#65 [Home] 스플레쉬 화면 와이어프레임 적용
  assets/fonts/Typo_SsangmunDongB.ttf
  assets/images/Logo.png
  lib/views/splash/splash_page.dart
  pubspec.yaml
Labels: fix

#70 [Plan] 지역/날짜 와이어프레임 적용
  lib/main.dart
  lib/views/calendar/calendar_page.dart
  lib/views/calendar/widgets/calendar_day_builder.dart
  lib/views/calendar/widgets/calendar_header.dart
  lib/views/calendar/widgets/calendar_widget.dart
  lib/views/plan/location_setting/district_setting_page.dart
  lib/views/plan/location_setting/province_setting_page.dart
  lib/views/plan/location_setting/widgets/district_box_item.dart
  lib/views/plan/location_setting/widgets/district_box_list.dart
  lib/views/plan/location_setting/widgets/province_box_item.dart
  lib/views/plan/location_setting/widgets/province_box_list.dart
  lib/views/plan/location_setting/widgets/selectable_box.dart
  lib/views/plan/location_setting/widgets/selectable_box_list.dart
  lib/views/preference/widgets/start_button.dart
  lib/views/splash/splash_page.dart
  pubspec.yaml
Labels: fix

#68 [Location] kakao검색 결과 기반 google map 마커 띄우기
  ios/Runner/AppDelegate.swift
  lib/models/map_state.dart
  lib/providers/map_provider.dart
  lib/repositories/map_repository.dart
  lib/utills/latlng_helper.dart
  lib/utills/map_utils.dart
  lib/viewmodels/map_view_model.dart
  lib/views/location/map_page.dart
  lib/views/location/widgets/map_display.dart
  lib/views/location/widgets/place_card.dart
  lib/views/location/widgets/place_carousel.dart
  lib/views/plan/schedule/widgets/schedule_app_bar.dart
Labels: feat

#72 [Home] 홈화면 ui 와이어프레임 적용
  assets/images/image14.png
  assets/images/image15.png
  assets/images/image17.png
  assets/images/image21.png
  assets/images/image22.png
  assets/images/image24.png
  assets/images/image25.png
  assets/images/image26.png
  assets/images/image27.png
  lib/core/widgets/bottom_bar.dart
  lib/core/widgets/svg_icon.dart
  lib/views/home/home_page.dart
  lib/views/home/recommended_place/recommended_place_detail_page.dart
  lib/views/home/recommended_place/recommended_places_list_page.dart
  lib/views/home/recommended_place/recommended_restaurant_detail_page.dart
  lib/views/home/recommended_place/recommended_restaurant_list_page.dart
  lib/views/home/recommended_place/widgets/recommended_place_list_card.dart
  lib/views/home/recommended_place/widgets/recommended_restaurant_list_card.dart
  lib/views/home/widgets/info_banner.dart
  lib/views/home/widgets/recommended_places_list.dart
  lib/views/home/widgets/recommended_restaurants_list.dart
  lib/views/home/widgets/section_title.dart
  lib/views/home/widgets/travel_register_button.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#84 [Plan] 검색페이지 와이어 프레임 적용 및 최근검색어 저장 기능 추가
  lib/providers/recent_search_provider.dart
  lib/repositories/search_history_repository.dart
  lib/views/home/widgets/travel_register_button.dart
  lib/views/plan/place_search/place_search_page.dart
  lib/views/plan/place_search/widgets/plan_place_card.dart
  lib/views/plan/place_search/widgets/recent_search_section.dart
  lib/views/plan/place_search/widgets/search_bar.dart
  lib/views/plan/schedule/schedule_page.dart
  lib/views/plan/widgets/schedule_app_bar.dart
  pubspec.yaml
Labels: feat

#88 [AI] AI 추천 여행 일정 기능 구현 및 저장 방식 분리
  lib/repositories/plan_repository.dart
  lib/repositories/preference_test_repository.dart
  lib/repositories/schedule_repository.dart
  lib/services/ai_service.dart
  lib/utills/date_utils.dart
  lib/viewmodels/schedule_view_model.dart
  lib/views/plan/schedule/schedule_page.dart
  lib/views/plan/schedule/widgets/ai_button.dart
  lib/views/plan/schedule/widgets/ai_type_select_popup.dart
Labels: feat

#92 [Plan] 지역/날짜 데이터베이스 연동
  lib/providers/calendar_locaion_provider.dart
  lib/repositories/calendar_location_repository.dart
  lib/viewmodels/calendar_location_view_model.dart
  lib/viewmodels/calendar_view_model.dart
  lib/views/calendar/calendar_page.dart
  lib/views/plan/location_setting/district_setting_page.dart
  lib/views/plan/location_setting/province_setting_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
Labels: feat

#94 [Location] 지도 페이지 디자인 적용
  assets/icons/map_pin.svg
  lib/utills/map_utils.dart
  lib/utills/marker_helper.dart
  lib/viewmodels/map_view_model.dart
  lib/views/location/map_page.dart
  lib/views/location/widgets/day_tab_bar.dart
  lib/views/location/widgets/map_display.dart
  lib/views/location/widgets/map_page_app_bar.dart
  lib/views/location/widgets/place_card.dart
Labels: fix

#96 [Login] 로그인 상태 전역관리 및 홈/로그인 화면 분기
  ios/Podfile.lock
  lib/main.dart
  lib/providers/auth_provider.dart
  lib/repositories/app_user_repository.dart
  lib/viewmodels/auth_view_model.dart
  lib/views/splash/splash_page.dart
Labels: feat

#100 [AI] ai추천받기와 카카오맵 매핑
  lib/repositories/preference_test_repository.dart
  lib/utills/ai_route_helper.dart
  lib/views/plan/schedule/widgets/ai_button.dart
  lib/views/plan/schedule/widgets/ai_type_select_popup.dart
  lib/views/plan/schedule/widgets/type_select_item.dart
Labels: feat

#103 [MyPage] 프로필 수정 페이지 와이어프레임 적용 및 프로필 업데이트 로직 수정, 적용
  lib/constants/app_text_styles.dart
  lib/core/validators.dart
  lib/main.dart
  lib/repositories/app_user_repository.dart
  lib/viewmodels/profile_view_model.dart
  lib/views/my_page/sheet/edit_profile_page.dart
  lib/views/my_page/sheet/edit_profile_sheet.dart
  lib/views/my_page/widgets/my_profile_screen.dart
  lib/views/onboarding/onboarding_page_set_profile.dart
  lib/views/onboarding/terms_agreement_bottom_sheet.dart
  lib/views/onboarding/widgets/check_duplicate_button.dart
  lib/views/onboarding/widgets/duplicate_button_themes.dart
  lib/views/widgets/edit_nickname.dart
  lib/views/widgets/next_button.dart
Labels: feat

#106 [Plan] 지역/캘린더 + 세부 계획 파이어베이스 통합 연결
  lib/repositories/calendar_location_repository.dart
  lib/viewmodels/auth_view_model.dart
  lib/viewmodels/calendar_location_view_model.dart
  lib/views/home/widgets/travel_register_button.dart
  lib/views/plan/location_setting/district_setting_page.dart
  lib/views/plan/schedule/schedule_page.dart
  lib/views/plan/schedule/widgets/schedule_bottom_button.dart
Labels: fix

#104 [Home] 사용자 위치 기반 명소,맛집 필터링
  lib/models/home_place.dart
  lib/models/home_state.dart
  lib/models/place.dart
  lib/providers/home_view_model_provider.dart
  lib/providers/location_provider.dart
  lib/providers/neardy_place_service_provider.dart
  lib/providers/place_search_service_provider.dart
  lib/providers/search_provider.dart
  lib/providers/selected_tag_provider.dart
  lib/repositories/location_repository.dart
  lib/services/nearby_place_service.dart
  lib/services/place_search_service.dart
  lib/viewmodels/home_view_model.dart
  lib/views/home/home_page.dart
  lib/views/home/recommended_place/recommended_place_detail_page.dart
  lib/views/home/recommended_place/recommended_places_list_page.dart
  lib/views/home/recommended_place/recommended_restaurant_detail_page.dart
  lib/views/home/recommended_place/recommended_restaurant_list_page.dart
  lib/views/home/recommended_place/widgets/hashtag_selector.dart
  lib/views/home/recommended_place/widgets/image_slider.dart
  lib/views/home/recommended_place/widgets/location_row.dart
  lib/views/home/recommended_place/widgets/place_description.dart
  lib/views/home/recommended_place/widgets/place_info_section.dart
  lib/views/home/recommended_place/widgets/place_map_view.dart
  lib/views/home/recommended_place/widgets/recommended_carousel.dart
  lib/views/home/recommended_place/widgets/recommended_place_list_card.dart
  lib/views/home/recommended_place/widgets/recommended_restaurant_list_card.dart
  lib/views/home/widgets/recommended_places_list.dart
  lib/views/home/widgets/recommended_restaurants_list.dart
  pubspec.yaml
Labels: feat

#112 [Login] 로그인 시 온보딩/홈 분기 구현
  ios/Podfile.lock
  lib/main.dart
  lib/viewmodels/auth_view_model.dart
  lib/views/login/widgets/sns_login_bar.dart
  lib/views/my_page/sheet/edit_profile_page.dart
  lib/views/onboarding/onboarding_page.dart
  lib/views/onboarding/onboarding_page_start_test.dart
  lib/views/splash/splash_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat

#111 [Plan] 사용자 선택 지역 기반 검색 필터링
  lib/providers/search_provider.dart
  lib/services/place_search_service.dart
  lib/viewmodels/search_view_model.dart
  lib/views/plan/place_search/place_search_page.dart
  lib/views/plan/schedule/schedule_page.dart
Labels: feat

#120 [Etc] 바텀바 스택 및 터치 액션 조정
  lib/core/widgets/bottom_bar.dart
  lib/providers/bottom_bar_provider.dart
  lib/views/home/recommended_place/recommended_places_list_page.dart
Labels: fix

#122 [Plan] 캘린더 여행 날짜 UI 적용
  lib/views/calendar/calendar_page.dart
Labels: fix

#117 [Preference] 성향테스트 ui 오류 수정,ai추천받기 인디케이터 추가
  lib/main.dart
  lib/views/plan/schedule/widgets/ai_type_select_popup.dart
  lib/views/preference/widgets/option_button.dart
  lib/views/preference/widgets/result_view.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#127 [Home] 홈 상단 여행날짜 d-day UX조정
  lib/main.dart
  lib/repositories/calendar_location_repository.dart
  lib/viewmodels/calendar_location_view_model.dart
  lib/views/home/widgets/info_banner.dart
Labels: feat, fix

#135 [Etc] 바텀바 개선 및 기타 UX 조정
  lib/core/widgets/bottom_bar.dart
  lib/views/plan/location_setting/widgets/district_box_item.dart
  lib/views/plan/schedule/schedule_page.dart
  lib/views/plan/widgets/schedule_app_bar.dart
Labels: fix

#134 [MyPage] 여행 일정/성향 리스트 마이페이지에서 표시 및 상세 페이지 연결
  devtools_options.yaml
  lib/constants/app_text_styles.dart
  lib/core/format_month_day.dart
  lib/core/format_region.dart
  lib/models/profile_state.dart
  lib/providers/schedule_provider.dart
  lib/repositories/calendar_location_repository.dart
  lib/repositories/preference_test_repository.dart
  lib/repositories/schedule_repository.dart
  lib/viewmodels/preference_test_view_model.dart
  lib/viewmodels/profile_view_model.dart
  lib/viewmodels/schedule_view_model.dart
  lib/views/my_page/plan_list_page.dart
  lib/views/my_page/preference_list_page.dart
  lib/views/my_page/sheet/edit_profile_page.dart
  lib/views/my_page/widgets/my_page_list_item.dart
  lib/views/my_page/widgets/my_page_menu.dart
  lib/views/my_page/widgets/my_profile_screen.dart
  lib/views/onboarding/widgets/select_gender.dart
  lib/views/plan/schedule/schedule_page.dart
  lib/views/preference/preference_loading_page.dart
  lib/views/preference/preference_test_page.dart
  lib/views/preference/widgets/result_action_buttons.dart
  lib/views/preference/widgets/result_view.dart
  pubspec.yaml
Labels: feat

#139 [etc] readMe 작성
  README.md
  lib/main.dart
Labels: feat

#142 feat: xcode 설정
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
Labels: feat

#152 [refactor] kakao api 429오류 대응 및 누락된 설정파일 재설정
  ios/Runner/AppDelegate.swift
  lib/services/plan/place_search_service.dart
  lib/viewmodels/plan/schedule_view_model.dart
  lib/views/plan/plan/widgets/schedule_app_bar.dart
Labels: refactory

#164 [Refactor] 로그인, 온보딩, 마이페이지 코드정리
  ios/Podfile.lock
  lib/models/user/auth_state.dart
  lib/models/user/terms_agreement_state_model.dart
  lib/providers/user/auth_view_model_provider.dart
  lib/providers/user/profile_view_model_provider.dart
  lib/providers/user/terms_agreement_view_model_provider.dart
  lib/repositories/user/app_user_repository.dart
  lib/services/user/auth_service.dart
  lib/utills/validators.dart
  lib/viewmodels/plan/calendar_location_view_model.dart
  lib/viewmodels/user/auth_view_model.dart
  lib/viewmodels/user/profile_view_model.dart
  lib/viewmodels/user/terms_agreement_view_model.dart
  lib/views/home/widgets/info_banner.dart
  lib/views/my_page/edit_profile_page.dart
  lib/views/my_page/my_page.dart
  lib/views/my_page/plan_list_page.dart
  lib/views/my_page/preference_list_page.dart
  lib/views/my_page/widgets/my_page_list_item.dart
  lib/views/my_page/widgets/my_profile_screen.dart
  lib/views/plan/plan/location_setting/widgets/save_button.dart
  lib/views/user/login/login_page.dart
  lib/views/user/login/widgets/sns_login_bar.dart
  lib/views/user/onboarding/onboarding_page.dart
  lib/views/user/onboarding/terms_agreement_bottom_sheet.dart
  lib/views/user/onboarding/widgets/check_duplicate_button.dart
  lib/views/user/onboarding/widgets/custom_check_toggle.dart
  lib/views/user/onboarding/widgets/duplicate_button_themes.dart
  lib/views/user/onboarding/widgets/edit_birth_date.dart
  lib/views/user/onboarding/widgets/select_gender.dart
  lib/views/user/splash/splash_page.dart
  lib/views/widgets/edit_nickname.dart
  lib/views/widgets/edit_profile_image.dart
  lib/views/widgets/user_next_button.dart
Labels: refactory

#156 [Refactor]성향 테스트 기능 구조 리팩토링 및 홈폴더,성향테스트 폴더 공통 색상(AppColors) 적용
  lib/core/ai_route_helper.dart
  lib/main.dart
  lib/providers/preference/preference_test_provider.dart
  lib/repositories/plan/plan_repository.dart
  lib/repositories/preference/preference_test_repository.dart
  lib/services/preference/preference_test_service.dart
  lib/viewmodels/preference/preference_test_state_notifier.dart
  lib/viewmodels/preference/preference_test_view_model.dart
  lib/views/home/home_page.dart
  lib/views/home/recommended_place/recommended_place_detail_page.dart
  lib/views/home/recommended_place/recommended_places_list_page.dart
  lib/views/home/recommended_place/recommended_restaurant_list_page.dart
  lib/views/home/recommended_place/widgets/hashtag_selector.dart
  lib/views/home/recommended_place/widgets/place_info_section.dart
  lib/views/home/recommended_place/widgets/recommended_carousel.dart
  lib/views/home/recommended_place/widgets/recommended_place_list_card.dart
  lib/views/home/recommended_place/widgets/recommended_restaurant_list_card.dart
  lib/views/home/widgets/info_banner.dart
  lib/views/home/widgets/recommended_places_list.dart
  lib/views/home/widgets/recommended_restaurants_list.dart
  lib/views/home/widgets/section_title.dart
  lib/views/home/widgets/travel_register_button.dart
  lib/views/my_page/preference_list_page.dart
  lib/views/plan/plan/schedule/schedule_page.dart
  lib/views/preference/preference_intro_page_2.dart
  lib/views/preference/preference_loading_page.dart
  lib/views/preference/preference_test_page.dart
  lib/views/preference/widgets/intro_header.dart
  lib/views/preference/widgets/next_button.dart
  lib/views/preference/widgets/option_button.dart
  lib/views/preference/widgets/page_indicator_bar.dart
  lib/views/preference/widgets/question_card.dart
  lib/views/preference/widgets/result_action_buttons.dart
  lib/views/preference/widgets/result_view.dart
  lib/views/preference/widgets/result_view_detail.dart
  lib/views/preference/widgets/scroll_bar_indicator.dart
  lib/views/preference/widgets/start_button.dart
  lib/views/preference/widgets/survey_preview_item.dart
Labels: refactory

#170 [Design] 스케줄 페이지, 검색, 지도 세부 디자인 수정
  assets/icons/check-circle.svg
  assets/icons/chevron-down.svg
  assets/icons/chevron-up.svg
  assets/icons/map.svg
  assets/icons/menu.svg
  assets/icons/search.svg
  lib/viewmodels/plan/search_view_model.dart
  lib/views/plan/location/map_page.dart
  lib/views/plan/location/widgets/day_tab_bar.dart
  lib/views/plan/location/widgets/map_display.dart
  lib/views/plan/location/widgets/place_card.dart
  lib/views/plan/plan/place_search/place_search_page.dart
  lib/views/plan/plan/place_search/widgets/confirm_add_button.dart
  lib/views/plan/plan/place_search/widgets/plan_place_card.dart
  lib/views/plan/plan/place_search/widgets/recent_search_section.dart
  lib/views/plan/plan/place_search/widgets/search_bar.dart
  lib/views/plan/plan/schedule/schedule_page.dart
  lib/views/plan/plan/schedule/widgets/ai_button.dart
  lib/views/plan/plan/schedule/widgets/bullet.dart
  lib/views/plan/plan/schedule/widgets/day_schedule_section.dart
  lib/views/plan/plan/schedule/widgets/ground_circle_icon.dart
  lib/views/plan/plan/schedule/widgets/schedule_bottom_button.dart
  lib/views/plan/plan/schedule/widgets/schedule_place_card.dart
  lib/views/plan/plan/widgets/schedule_app_bar.dart
Labels: fix

#178 [Location] 지도 페이지 전체 루트 시각화
  lib/models/home/home_place.dart
  lib/viewmodels/plan/map_view_model.dart
  lib/views/plan/location/map_page.dart
  lib/views/plan/location/widgets/place_card.dart
  lib/views/plan/location/widgets/place_carousel.dart
Labels: feat

#181 [Preference] 여행 성향테스트 삭제 기능 추가
  lib/providers/preference/preference_test_provider.dart
  lib/repositories/preference/preference_test_repository.dart
  lib/viewmodels/preference/preference_test_state_notifier.dart
  lib/views/my_page/preference_list_page.dart
  lib/views/preference/widgets/result_view.dart
Labels: feat

#184 [AI]일정 내 장소들을 중심 좌표 기준 거리순으로 재정렬하는 기능 구현
  lib/utills/distance_sort.dart
  lib/views/plan/plan/schedule/schedule_page.dart
  lib/views/plan/plan/schedule/widgets/distance_sort_button.dart
Labels: feat

#189 [MyPage] 알림기능 활성화
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  lib/main.dart
  lib/utills/notification_helper.dart
  lib/utills/notification_setting.dart
  lib/views/my_page/settings/notification_setting_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugins.cmake
Labels: feat

#191 [Etc] 글작성 저장 Ui + 저장 수정 삭제 로직 완료, 디테일페이지 Ui + 수정,삭제 완료, 리스트페이지 개발용으로 테스트
  lib/core/widgets/bottom_bar.dart
  lib/models/post/post_model.dart
  lib/providers/post/post_provider.dart
  lib/repositories/post/post_repository.dart
  lib/utills/date_utils.dart
  lib/viewmodels/post/post_view_model.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/post_list_page.dart
  lib/views/post/post_write_page.dart
  lib/views/post/widgets/detail/post_detail_appbar.dart
  lib/views/post/widgets/detail/post_detail_content.dart
  lib/views/post/widgets/detail/post_detail_header.dart
  lib/views/post/widgets/detail/post_detail_images.dart
  lib/views/post/widgets/detail/post_detail_tags_and_meta.dart
  lib/views/post/widgets/write/bottom_sheet_category.dart
  lib/views/post/widgets/write/category_chip.dart
  lib/views/post/widgets/write/image_preview_list.dart
  lib/views/post/widgets/write/post_action_buttons.dart
  lib/views/post/widgets/write/post_location_category.dart
  lib/views/post/widgets/write/post_text_fields.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#197 [Preference] 성향테스트 페이지_인디케이터_바 오버플로우 수정
  lib/views/preference/widgets/page_indicator_bar.dart
Labels: fix

#199 [Etc] 스플래시 페이지, 홈페이지, 성향 결과 페이지의 유저정보 확인 불가 오류 픽스
  lib/repositories/user/app_user_repository.dart
  lib/services/user/auth_service.dart
  lib/viewmodels/user/app_user_view_model.dart
  lib/viewmodels/user/auth_view_model.dart
  lib/views/home/home_page.dart
  lib/views/home/widgets/info_banner.dart
  lib/views/preference/widgets/result_view.dart
  lib/views/user/login/widgets/sns_login_bar.dart
  lib/views/user/onboarding/onboarding_page.dart
  lib/views/user/onboarding/terms_agreement_bottom_sheet.dart
  lib/views/user/splash/splash_page.dart
Labels: fix

#202 [Preference]성향테스트인트로 닉네임 나오게 변경
  lib/views/preference/preference_intro_page_2.dart
Labels: fix

#188 [Etc] 신고 기능 로직 구현
  lib/models/scoial/report.dart
  lib/models/scoial/reported_comment.dart
  lib/models/scoial/reported_post.dart
  lib/providers/scoial/admin_report_provider.dart
  lib/providers/scoial/report_provider.dart
  lib/repositories/scoial/admin_report_repository.dart
  lib/repositories/scoial/report_repository.dart
  lib/viewmodels/scoial/admin_report_view_model.dart
  lib/viewmodels/scoial/report_view_model.dart
  lib/viewmodels/scoial/widgets/reported_card.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/report/admin_report_screen.dart
  lib/views/post/report/report_test.dart
  lib/views/post/widgets/detail/show_report_reason_dialog.dart
Labels: feat

#211 [Etc] 관리자 권한 부여
  .gitignore
  functions/index.js
  lib/repositories/scoial/admin_report_repository.dart
  lib/viewmodels/scoial/report_view_model.dart
  lib/viewmodels/user/admin/admin_guard.dart
  lib/viewmodels/user/admin/admin_view_model.dart
  lib/views/my_page/settings/setting_page.dart
  lib/views/post/report/admin_report_screen.dart
  lib/views/post/report/report_test.dart
  lib/views/user/admin/admin_entry.dart
  lib/views/user/admin/admin_page.dart
  lib/views/user/admin/admin_report_entry.dart
  lib/views/user/admin/admin_report_screen.dart
  lib/views/user/admin/widgets/reported_card.dart
  pubspec.yaml
Labels: feat

#214 [Home] 장소 상세보기 저장 기능(스크랩)
  lib/models/home/home_place.dart
  lib/providers/home/scrap_provider.dart
  lib/repositories/home/scrap_repository.dart
  lib/viewmodels/home/scrap_view_model.dart
  lib/viewmodels/user/scrap_list_view_model.dart
  lib/views/home/recommended_place/recommended_place_detail_page.dart
  lib/views/my_page/my_scrap_list_page.dart
  lib/views/my_page/widgets/my_page_menu.dart
Labels: feat

#219 [Post] 커뮤니티 페이지 구현
  lib/constants/app_other_styles.dart
  lib/constants/app_text_styles.dart
  lib/constants/post_tags_list.dart
  lib/models/post/post_list_state_model.dart
  lib/models/post/post_model.dart
  lib/providers/post/post_list_view_model_provider.dart
  lib/repositories/post/post_list_repository.dart
  lib/utills/format_time_ago.dart
  lib/utills/throttler.dart
  lib/viewmodels/post/post_list_view_model.dart
  lib/viewmodels/post/post_view_model.dart
  lib/views/post/post_list_page.dart
  lib/views/post/widgets/list/bottom_sheet_category_filter.dart
  lib/views/post/widgets/list/more_tag_button.dart
  lib/views/post/widgets/list/post_item.dart
  lib/views/post/widgets/list/post_list_view.dart
  lib/views/post/widgets/list/post_loading_item.dart
  lib/views/post/widgets/list/tag_bar.dart
  lib/views/post/widgets/list/time_ago_text.dart
  lib/views/post/widgets/write/bottom_sheet_category.dart
  lib/views/post/widgets/write/write_fab.dart
Labels: feat

#218 [Post] 좋아요 기능 추가 마이페이지 내가 좋아요한 게시글 기능 추가
  lib/models/post/like_model.dart
  lib/models/post/post_model.dart
  lib/providers/post/like_provider.dart
  lib/repositories/post/like_repository.dart
  lib/viewmodels/post/like_viewmodel.dart
  lib/views/my_page/like_list_page.dart
  lib/views/my_page/widgets/my_page_menu.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/widgets/detail/post_detail_tags_and_meta.dart
Labels: feat

#224 [Etc] 피그마 디자인 반영
  assets/icons/alert-circle.svg
  lib/core/widgets/custom_toast.dart
  lib/views/home/recommended_place/recommended_place_detail_page.dart
  lib/views/home/recommended_place/recommended_places_list_page.dart
  lib/views/home/recommended_place/recommended_restaurant_list_page.dart
  lib/views/home/recommended_place/widgets/image_slider.dart
  lib/views/home/recommended_place/widgets/location_row.dart
  lib/views/home/recommended_place/widgets/recommended_place_list_card.dart
  lib/views/home/recommended_place/widgets/recommended_restaurant_list_card.dart
  lib/views/my_page/my_scrap_list_page.dart
  lib/views/my_page/plan_list_page.dart
  lib/views/my_page/widgets/confirm_dialog.dart
  lib/views/plan/plan/schedule/schedule_page.dart
  lib/views/plan/plan/schedule/widgets/schedule_confirm_dialog.dart
  lib/views/plan/plan/widgets/schedule_app_bar.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/widgets/detail/custom_radio_circle.dart
  lib/views/post/widgets/detail/show_report_reason_dialog.dart
Labels: fix, refactory

#241 [MyPage] 탈퇴 시 확인 팝업 표시
  lib/repositories/user/app_user_repository.dart
  lib/viewmodels/user/profile_view_model.dart
  lib/views/my_page/widgets/confirm_dialog.dart
  lib/views/my_page/widgets/custom_dialog.dart
  lib/views/my_page/widgets/delete_account_button.dart
  lib/views/user/onboarding/onboarding_page.dart
Labels: feat

#244 [ETC] README 트러블 슈팅, 영상 추가
  README.md
Labels: feat

#246 [Post] 댓글 답글 기능 구현
  lib/models/post/comment_model.dart
  lib/repositories/post/comment_repository.dart
  lib/utills/format_time_ago.dart
  lib/views/post/ comment/comment_detail_page.dart
  lib/views/post/ comment/comment_section.dart
  lib/views/post/ comment/widgets/comment_item.dart
  lib/views/post/ comment/widgets/reply_preivew.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/widgets/detail/comment_section.dart
Labels: feat

#249 [MyPage] 계정 관리 페이지 피그마 적용
  lib/views/my_page/settings/account_setting_page.dart
  lib/views/my_page/widgets/account_info.dart
Labels: feat

#252 [ETC] snacbar toast로 변경, 저장 이슈 수정
  lib/views/home/recommended_place/recommended_place_detail_page.dart
  lib/views/my_page/plan_list_page.dart
  lib/views/plan/plan/schedule/schedule_page.dart
Labels: fix, refactory

#251 [Design]게시글 실시간 반영 및 모달/디자인 UI 개선 작업
  assets/gif/gif.gif
  lib/viewmodels/post/post_list_view_model.dart
  lib/viewmodels/post/post_view_model.dart
  lib/views/home/recommended_place/recommended_place_detail_sheet.dart
  lib/views/my_page/like_list_page.dart
  lib/views/my_page/my_post_page.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/post_write_page.dart
  lib/views/post/widgets/detail/popup.dart
  lib/views/post/widgets/detail/post_detail_content.dart
  lib/views/post/widgets/detail/post_detail_header.dart
  lib/views/post/widgets/list/post_list_view.dart
  lib/views/post/widgets/write/bottom_sheet_category.dart
  lib/views/post/widgets/write/write_fab.dart
  lib/views/preference/preference_loading_page.dart
  pubspec.yaml
Labels: fix, refactory

#248 [ETC]구글맵 키 숨기기
  .gitignore
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
Labels: refactory

#254 [POST] 댓글 신고하기 피그마 반영
  ios/Podfile.lock
  lib/views/post/ comment/comment_detail_page.dart
  lib/views/post/ comment/widgets/action_item.dart
  lib/views/post/ comment/widgets/comment_item.dart
  pubspec.lock
Labels: refactory

#260 [Etc] 북마크 클릭 시 상세페이지 이동 및 디자인 수정
  lib/views/my_page/my_scrap_list_page.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/post_write_page.dart
  lib/views/post/widgets/write/confirm_dialog.dart
Labels: feat, fix
