Repository jinsung99123/travel_muse_app, pull requests merged in 2025-07, with the labels that each got.

#265 [AI]여행일수 10일 제한
  lib/core/ai_route_helper.dart
Labels: feat

#272 [Post] 포스트 리스트 표시 버그 3종 픽스
  lib/viewmodels/post/post_list_view_model.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/post_write_page.dart
  lib/views/post/widgets/list/tag_bar.dart
Labels: fix

#273 [MyPage] 마이페이지 및 댓글 기능 피그마 적용
  lib/views/home/widgets/section_title.dart
  lib/views/my_page/my_page.dart
  lib/views/my_page/settings/notification_setting_page.dart
  lib/views/my_page/settings/service_term_page.dart
  lib/views/my_page/settings/setting_page.dart
  lib/views/my_page/widgets/my_page_menu.dart
  lib/views/post/ comment/comment_detail_page.dart
  lib/views/post/ comment/comment_section.dart
  lib/views/post/ comment/widgets/comment_item.dart
  lib/views/post/ comment/widgets/reply_preivew.dart
Labels: fix

#279 [Post]실시간 댓글수 답글까지 수정 완료
  lib/repositories/post/comment_repository.dart
  lib/views/post/ comment/comment_section.dart
Labels: fix

#284 [location] 지도 페이지 성능이슈 해결
  lib/views/plan/location/map_page.dart
  lib/views/plan/location/widgets/place_carousel.dart
  lib/views/plan/plan/widgets/schedule_app_bar.dart
Labels: refactory

#287 [Location] 홈화면 명소 추천 기본 위경도추가, 지도 위치권한 팝업 불러오기
  lib/viewmodels/home/home_view_model.dart
  lib/viewmodels/plan/schedule_view_model.dart
  lib/views/home/home_page.dart
  lib/views/home/recommended_place/recommended_places_list_page.dart
  lib/views/home/recommended_place/recommended_restaurant_list_page.dart
  lib/views/home/widgets/recommended_places_list.dart
  lib/views/home/widgets/recommended_restaurants_list.dart
  lib/views/plan/plan/place_search/place_search_page.dart
  lib/views/plan/plan/schedule/widgets/map_confirm_dialog.dart
  lib/views/plan/plan/widgets/schedule_app_bar.dart
Labels: feat, refactory

#288 [Etc] 앱 아이콘 추가
  ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/120 1.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/120.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/152.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/167.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/180.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/20.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/29 1.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/29.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/40 1.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/40 2.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/40.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/58 1.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/58.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/60.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/76.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/80 1.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/80.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/87.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  pubspec.lock
Labels: feat

#296 [AI] EasyLoading 스타일 적용 및 AI 추천 결과 팝업 UI 구현
  lib/main.dart
  lib/views/plan/plan/schedule/widgets/ai_button.dart
  lib/views/plan/plan/schedule/widgets/ai_type_select_popup.dart
  lib/views/plan/plan/schedule/widgets/show_ai_route_result_popup.dart
  lib/views/widgets/easy_loading_config.dart
Labels: feat

#291 [Post] 포스트 상세 페이지 로딩시 기본 프로필 수정
  lib/views/my_page/widgets/my_profile_screen.dart
  lib/views/post/widgets/detail/post_detail_header.dart
Labels: fix

#304 [Plan] 일정 전체 드래그앤 드랍 기능 구현
  assets/icons/plus-circle.svg
  assets/icons/x-circle.svg
  lib/views/plan/plan/schedule/schedule_page.dart
  lib/views/plan/plan/schedule/widgets/day_schedule_list.dart
  lib/views/plan/plan/schedule/widgets/day_schedule_section.dart
  lib/views/plan/plan/schedule/widgets/schedule_place_card.dart
  pubspec.yaml
Labels: feat

#310 [AI]썸네일 이미지 오류 , ai 추천 결과 팝업 오버플로우 해결
  android/app/build.gradle.kts
  assets/images/default_image.jpg
  lib/utills/notification_helper.dart
  lib/views/plan/location/widgets/place_card.dart
  lib/views/plan/plan/schedule/widgets/schedule_place_card.dart
  lib/views/plan/plan/schedule/widgets/show_ai_route_result_popup.dart
Labels: fix

#312 [Etc] 코드 리팩토링
  lib/constants/app_text_styles.dart
  lib/core/bottom_bar_provider.dart
  lib/core/bottom_nav_bar_provider.dart
  lib/core/widgets/bottom_nav_bar.dart
  lib/repositories/user/app_user_repository.dart
  lib/repositories/user/terms_repository.dart
  lib/utills/validators.dart
  lib/viewmodels/post/post_list_view_model.dart
  lib/viewmodels/user/app_user_view_model.dart
  lib/viewmodels/user/profile_view_model.dart
  lib/viewmodels/user/user_agreement_view_model.dart
  lib/views/home/home_page.dart
  lib/views/home/widgets/recommended_places_list.dart
  lib/views/my_page/my_page.dart
  lib/views/my_page/my_scrap_list_page.dart
  lib/views/plan/plan/schedule/schedule_page.dart
  lib/views/post/post_list_page.dart
  lib/views/post/widgets/list/tag_bar.dart
  lib/views/tabs/community_tab.dart
  lib/views/tabs/home_tab.dart
  lib/views/tabs/my_page_tab.dart
  lib/views/tabs/recommended_places_tab.dart
  lib/views/user/login/widgets/sns_login_bar.dart
  lib/views/user/onboarding/terms_web_view_page.dart
  lib/views/user/onboarding/widgets/edit_birth_date.dart
  lib/views/user/onboarding/widgets/option_box.dart
  lib/views/user/onboarding/widgets/select_gender.dart
  lib/views/widgets/custom_back_button.dart
  lib/views/widgets/edit_nickname.dart
Labels: refactory

#314 [Etc] 담당파트 리팩토링
  lib/providers/post/like_provider.dart
  lib/providers/post/liked_post_list_provider.dart
  lib/providers/post/post_detail_view_model_provider.dart
  lib/services/plan/ai_service.dart
  lib/services/preference/preference_test_service.dart
  lib/utills/logger_util.dart
  lib/viewmodels/home/place_detail_view_model.dart
  lib/viewmodels/plan/map_view_model.dart
  lib/viewmodels/post/like_view_model.dart
  lib/viewmodels/post/liked_post_list_view_model.dart
  lib/viewmodels/post/my_posts_view_model.dart
  lib/viewmodels/post/post_detail_state.dart
  lib/viewmodels/post/post_detail_view_model.dart
  lib/viewmodels/post/post_view_model.dart
  lib/views/home/recommended_place/widgets/place_direction_info.dart
  lib/views/my_page/like_list_page.dart
  lib/views/my_page/my_post_page.dart
  lib/views/plan/location/map_page.dart
  lib/views/plan/plan/place_search/place_search_page.dart
  lib/views/plan/plan/schedule/schedule_page.dart
  lib/views/plan/plan/schedule/widgets/ai_button.dart
  lib/views/plan/plan/schedule/widgets/ai_type_select_popup.dart
  lib/views/plan/plan/schedule/widgets/show_ai_route_result_popup.dart
  lib/views/plan/plan/widgets/schedule_app_bar.dart
  lib/views/post/post_detail_page.dart
  lib/views/post/post_page.dart
  lib/views/post/post_write_page.dart
  lib/views/post/widgets/detail/post_detail_images.dart
  lib/views/post/widgets/write/confirm_dialog.dart
  lib/views/post/widgets/write/post_location_category.dart
  lib/views/post/widgets/write/write_fab.dart
  lib/views/preference/preference_intro_page_1.dart
  lib/views/preference/widgets/result_view.dart
  lib/views/preference/widgets/result_view_detail.dart
  pubspec.lock
  pubspec.yaml
Labels: refactory

#315 [Plan]일정 저장 후 네비게이터 설정 및 액션 추가
  lib/views/plan/plan/schedule/schedule_page.dart
Labels: fix
